spring.application.name=laba3
server.port=5050

spring.output.ansi.enabled=ALWAYS
spring.mvc.log-request-details=true
spring.web.locale=ru_RU

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cache=DEBUG
